# Generated by Django 6.1 on 2026-08-23 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_owner_role',
            field=models.BooleanField(default=False, help_text="The organization's built-in Owner role. Always has every permission and can't be edited or deleted — this is what guarantees an organization can never end up with nobody able to manage it. Only set automatically when an organization is created; there is no way to grant this to a role through the app."),
        ),
    ]
