# Generated by Django 6.1 on 2026-08-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_role_is_owner_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_borrow_items',
            field=models.BooleanField(default=False, help_text='Borrow items marked as borrowable, and mark them returned.'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_delete_items',
            field=models.BooleanField(default=False, help_text='Permanently delete an item from inventory.'),
        ),
        migrations.AlterField(
            model_name='role',
            name='can_remove_stock',
            field=models.BooleanField(default=False, help_text='Decrease stock quantity — the "Take" action.'),
        ),
    ]
