# Generated by Django 6.1 on 2026-08-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_rename_owner_role_to_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='is_owner_role',
            field=models.BooleanField(default=False, help_text='The organization\'s built-in Admin role (shown to users as "Admin" — this field name is historical). Always has every permission and can\'t be edited or deleted — this is what guarantees an organization can never end up with nobody able to manage it. Only set automatically when an organization is created; there is no way to grant this to a role through the app.'),
        ),
    ]
