# Generated by Django 6.1 on 2026-08-23 03:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='allow_borrow',
            field=models.BooleanField(default=False, help_text='Can be checked out temporarily and later returned — e.g. tools or equipment.'),
        ),
        migrations.AddField(
            model_name='item',
            name='allow_take',
            field=models.BooleanField(default=True, help_text='Can be permanently taken out of stock (consumed) — most items.'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='transaction_type',
            field=models.CharField(choices=[('ADD', 'Stock added'), ('REMOVE', 'Stock removed (taken)'), ('LOCATION_CHANGE', 'Location changed'), ('EXCEL_IMPORT', 'Bulk Excel import'), ('BORROW', 'Borrowed'), ('RETURN', 'Returned')], max_length=20),
        ),
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('borrowed_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, help_text='Optional — when it should come back.', null=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('borrowed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrowed_items', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_records', to='inventory.item')),
            ],
            options={
                'ordering': ['-borrowed_at'],
            },
        ),
    ]
