# Generated by Django 6.1 on 2026-08-23 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_item_allow_borrow_item_allow_take_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='track_quantity',
            field=models.BooleanField(default=True, help_text='Uncheck for items you don\'t want to count individually — e.g. bulk material ("a pile of sand") where only the location matters. Quantity, unit, reorder warnings, and the stock actions (+Stock / Take / Borrow) are all hidden for an item with this off.'),
        ),
    ]
