# Generated by Django 6.1 on 2026-08-23 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_item_track_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='location',
        ),
        migrations.RemoveField(
            model_name='stocktransaction',
            name='new_location',
        ),
        migrations.RemoveField(
            model_name='stocktransaction',
            name='previous_location',
        ),
        migrations.AddField(
            model_name='item',
            name='location_description',
            field=models.CharField(blank=True, help_text='Optional: aisle, building, address, etc.', max_length=255),
        ),
        migrations.AddField(
            model_name='item',
            name='location_name',
            field=models.CharField(blank=True, help_text='Where this item is kept — e.g. "Main Warehouse", "Rack 3".', max_length=150),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='new_location_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='previous_location_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
